version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:6
    container_name: ai-alert-manager-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    networks:
      - ai-alert-network

  # MongoDB GUI (optional)
  mongo-express:
    image: mongo-express
    container_name: ai-alert-manager-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - ai-alert-network

  # AI Alert Manager application
  ai-alert-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-alert-manager-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:rootpassword@mongodb:27017/alert-manager?authSource=admin
      - OPENAI_API_KEY="${OPENAI_API_KEY}"
      - SLACK_WEBHOOK_URL="${SLACK_WEBHOOK_URL}"
    depends_on:
      - mongodb
    networks:
      - ai-alert-network

  # Prometheus (for development/testing)
  prometheus:
    image: prom/prometheus:latest
    container_name: ai-alert-manager-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - ai-alert-network

  # Alert Manager (for development/testing)
  alertmanager:
    image: prom/alertmanager:latest
    container_name: ai-alert-manager-alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - ai-alert-network

volumes:
  mongodb_data:
  prometheus_data:

networks:
  ai-alert-network:
    driver: bridge