version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:6
    container_name: ai-alert-manager-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    networks:
      - ai-alert-network

  # AI Alert Manager application
  ai-alert-manager:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: ai-alert-manager-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:rootpassword@mongodb:27017/alert-manager?authSource=admin
      - LLM_PROVIDER=ollama
      - OLLAMA_ENDPOINT=http://host.docker.internal:11434
      - OLLAMA_MODEL=codellama
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - JWT_SECRET=${JWT_SECRET:-default-jwt-secret-for-development-only}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeMe!Now123}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb
     # - ollama
    networks:
      - ai-alert-network


volumes:
  mongodb_data:

networks:
  ai-alert-network:
    driver: bridge
