apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-alert-manager.fullname" . }}
  labels:
    {{- include "ai-alert-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ai-alert-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ai-alert-manager.selectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ai-alert-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: MONGODB_URI
              value: {{ .Values.config.mongo.uri }}
            - name: LLM_PROVIDER
              value: {{ .Values.config.llm.provider }}
            - name: OLLAMA_ENDPOINT
              value: {{ .Values.config.llm.endpoint }}
            - name: OLLAMA_MODEL
              value: {{ .Values.config.llm.model }}
            {{- if and .Values.config.slack.enabled .Values.config.slack.webhookSecretName }}
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.slack.webhookSecretName }}
                  key: {{ .Values.config.slack.webhookSecretKey }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}