{{- if and .Values.config.slack.enabled (not .Values.config.slack.webhookSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-alert-manager.fullname" . }}-slack-webhook
  labels:
    {{- include "ai-alert-manager.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.config.slack.webhookUrl | default "" | b64enc }}
{{- end }}