global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'ai-alert-manager'

receivers:
  - name: 'ai-alert-manager'
    webhook_configs:
      - url: 'http://ai-alert-manager:3000/webhook'
        send_resolved: true
