name: Release Helm Charts

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
      - '.github/workflows/helm-release.yml'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This permission is required to create releases
      packages: write  # This is needed if you're also pushing to GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Add Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      # Set up gh-pages branch if it doesn't exist
      - name: Create gh-pages branch if doesn't exist
        run: |
          if ! git ls-remote --heads origin gh-pages | grep gh-pages > /dev/null; then
            echo "Creating gh-pages branch"
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Create gh-pages branch"
            git push origin gh-pages
            git checkout -
          else
            echo "gh-pages branch already exists"
          fi
      
      - name: Initialize gh-pages with basic content
        run: |
          if git ls-remote --heads origin gh-pages | grep gh-pages > /dev/null; then
            echo "gh-pages branch exists, checking if empty"
            git checkout gh-pages
            if [ -z "$(ls -A | grep -v '.git')" ]; then
              echo "gh-pages branch is empty, initializing with index.yaml"
              echo "apiVersion: v1" > index.yaml
              echo "entries: {}" >> index.yaml
              echo "generated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> index.yaml
              git add index.yaml
              git commit -m "Initialize index.yaml"
              git push origin gh-pages
            fi
            git checkout -
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
          
      # Add manual packaging and indexing step with dependency update
      - name: Manual chart packaging if index is empty
        run: |
          # Check if index.yaml is empty
          git fetch origin gh-pages
          git checkout gh-pages
          ENTRIES_EMPTY=$(grep -c "entries: {}" index.yaml || true)
          git checkout -
          
          if [ "$ENTRIES_EMPTY" -gt 0 ]; then
            echo "Index appears to be empty, manually packaging charts..."
            # Debug chart structure
            echo "Chart structure:"
            find charts -type f | sort
            
            # Get chart directories
            CHART_DIRS=$(find ./charts -name Chart.yaml -exec dirname {} \;)
            
            if [ -z "$CHART_DIRS" ]; then
              echo "No Chart.yaml files found! Check your repository structure."
              exit 1
            fi
            
            echo "Found chart directories: $CHART_DIRS"
            
            # Debug Chart.yaml contents
            echo "Chart.yaml contents:"
            find ./charts -name Chart.yaml -exec echo {} \; -exec cat {} \; -exec echo "" \;
            
            # Update dependencies before packaging
            echo "Updating chart dependencies:"
            for dir in $CHART_DIRS; do
              echo "Updating dependencies for $dir"
              helm dependency update "$dir"
            done
            
            # Package charts
            echo "Packaging charts:"
            mkdir -p .cr-release-packages
            for dir in $CHART_DIRS; do
              echo "Packaging $dir"
              helm package "$dir" --destination .cr-release-packages/
            done
            
            echo "Package results:"
            ls -la .cr-release-packages/
            
            if [ "$(ls -A .cr-release-packages)" ]; then
              echo "Creating index.yaml:"
              helm repo index --url https://binyamse.github.io/PhoenixAlerts .cr-release-packages/
              cat .cr-release-packages/index.yaml
              
              echo "Updating gh-pages branch:"
              git checkout gh-pages
              cp .cr-release-packages/*.tgz .
              cp .cr-release-packages/index.yaml .
              git add *.tgz index.yaml
              git commit -m "Manual update of Helm repository"
              git push origin gh-pages
            else
              echo "No charts were packaged! Check for errors above."
            fi
          else
            echo "Index.yaml appears to have entries, skipping manual packaging."
          fi