{{- if not .Values.secrets.useExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phoenix-alerts.fullname" . }}
  labels:
    {{- include "phoenix-alerts.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mongodb.enabled }}
  mongodb-uri: {{ include "phoenix-alerts.mongodbUri" . | b64enc | quote }}
  {{- else if .Values.secrets.secretValues.mongodbUri }}
  mongodb-uri: {{ .Values.secrets.secretValues.mongodbUri | b64enc | quote }}
  {{- end }}
  
  # LLM API keys (only the relevant ones will be used based on the llm.provider setting)
  {{- if .Values.secrets.secretValues.openAiApiKey }}
  openai-api-key: {{ .Values.secrets.secretValues.openAiApiKey | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.secretValues.anthropicApiKey }}
  anthropic-api-key: {{ .Values.secrets.secretValues.anthropicApiKey | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.secretValues.azureOpenAiApiKey }}
  azure-openai-api-key: {{ .Values.secrets.secretValues.azureOpenAiApiKey | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.secretValues.azureOpenAiEndpoint }}
  azure-openai-endpoint: {{ .Values.secrets.secretValues.azureOpenAiEndpoint | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.secretValues.huggingfaceApiKey }}
  huggingface-api-key: {{ .Values.secrets.secretValues.huggingfaceApiKey | b64enc | quote }}
  {{- end }}
  
  # Common secrets
  {{- if .Values.secrets.secretValues.slackWebhookUrl }}
  slack-webhook-url: {{ .Values.secrets.secretValues.slackWebhookUrl | b64enc | quote }}
  {{- end }}
{{- end }}