apiVersion: v1
kind: Service
metadata:
  name: {{ include "phoenix-alerts.fullname" . }}-backend
  labels:
    {{- include "phoenix-alerts.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.service.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "phoenix-alerts.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "phoenix-alerts.fullname" . }}-frontend
  labels:
    {{- include "phoenix-alerts.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.service.frontend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "phoenix-alerts.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend